### ISSUE TITLE
Wiki formatting errors

### ISSUE THREAD

**Issue by MajickTek** [nerdyjem/apkmanager#2]
I have went through the wiki and fixed multiple formatting errors, all of which had to do with the hashtag.

In markdown, a space is required between your "###" and the word after it. This is due to how the characters are interpreted on GitHub. 

You can close this issue if you want, because I fixed everything. I didn't know where else to tell you this.

**Comment by nerdyjem** [comment]
Thanks, and I apologize that this is long dead/abandoned, feel free to fork/takeover if you want.
